gsheets_url:
  2022: https://docs.google.com/spreadsheets/d/1S_JpXXd-CKd7p3AQd_jgpk1j_8Alkh9537UYqGCbDxc
  2023: https://docs.google.com/spreadsheets/d/190S6XqgvRX0VKCFKUYLAbw7Lx7aOHzo4UbykPHSfFJ8
milking_charge: 300
no_milker: true
state: 2
